/* Adapted from the animated-group primitive generated by motion-primitives. */
import { motion } from 'motion/react'
import { Children, type ReactNode } from 'react'
import { motionTokens } from '../motion/motionTokens'

export function AnimatedGroup({ children, className = '' }: { children: ReactNode; className?: string }) {
  const items = Children.toArray(children)
  const animateEntrance = items.length <= 12
  return (
    <motion.div className={className} initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: animateEntrance ? motionTokens.stagger.normal : 0, delayChildren: animateEntrance ? 0.02 : 0 } } }}>
      {items.map((child, index) => <motion.div key={index} variants={{ hidden: { opacity: animateEntrance && index < 12 ? 0 : 1, y: animateEntrance && index < 12 ? motionTokens.distance.md : 0 }, visible: { opacity: 1, y: 0 } }} transition={{ duration: motionTokens.duration.normal, ease: motionTokens.ease.standard }}>{child}</motion.div>)}
    </motion.div>
  )
}
